package com.bigroad.model.db;

// Generated 2015-4-25 13:01:25 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TAuthorization generated by hbm2java
 */
@Entity
@Table(name = "T_authorization", catalog = "CloudFiles")
public class TAuthorization implements java.io.Serializable {

	private String userId;
	private String token;
	private Date updateDate;

	public TAuthorization() {
	}

	public TAuthorization(String userId, String token, Date updateDate) {
		this.userId = userId;
		this.token = token;
		this.updateDate = updateDate;
	}

	@Id
	@Column(name = "userId", unique = true, nullable = false, length = 100)
	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	@Column(name = "token", nullable = false, length = 100)
	public String getToken() {
		return this.token;
	}

	public void setToken(String token) {
		this.token = token;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updateDate", nullable = false, length = 19)
	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

}
