package com.bigroad.model.db;

// Generated 2015-5-1 16:53:11 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TCompany generated by hbm2java
 */
@Entity
@Table(name = "T_company", catalog = "CloudFiles")
public class TCompany implements java.io.Serializable {

	private String companyId;
	private String companyName;
	private String companyPassword;
	private String logoAddress;
	private String organizationCode;
	private String companyAddress;
	private String linkMan;
	private String linkManTelephone;
	private Double companySpaceSize;
	private Double companyUsedSpace;

	public TCompany() {
	}

	public TCompany(String companyId) {
		this.companyId = companyId;
	}

	public TCompany(String companyId, String companyName,
			String companyPassword, String logoAddress,
			String organizationCode, String companyAddress, String linkMan,
			String linkManTelephone, Double companySpaceSize,
			Double companyUsedSpace) {
		this.companyId = companyId;
		this.companyName = companyName;
		this.companyPassword = companyPassword;
		this.logoAddress = logoAddress;
		this.organizationCode = organizationCode;
		this.companyAddress = companyAddress;
		this.linkMan = linkMan;
		this.linkManTelephone = linkManTelephone;
		this.companySpaceSize = companySpaceSize;
		this.companyUsedSpace = companyUsedSpace;
	}

	@Id
	@Column(name = "companyID", unique = true, nullable = false, length = 100)
	public String getCompanyId() {
		return this.companyId;
	}

	public void setCompanyId(String companyId) {
		this.companyId = companyId;
	}

	@Column(name = "companyName", length = 45)
	public String getCompanyName() {
		return this.companyName;
	}

	public void setCompanyName(String companyName) {
		this.companyName = companyName;
	}

	@Column(name = "companyPassword", length = 45)
	public String getCompanyPassword() {
		return this.companyPassword;
	}

	public void setCompanyPassword(String companyPassword) {
		this.companyPassword = companyPassword;
	}

	@Column(name = "logoAddress", length = 45)
	public String getLogoAddress() {
		return this.logoAddress;
	}

	public void setLogoAddress(String logoAddress) {
		this.logoAddress = logoAddress;
	}

	@Column(name = "organizationCode", length = 45)
	public String getOrganizationCode() {
		return this.organizationCode;
	}

	public void setOrganizationCode(String organizationCode) {
		this.organizationCode = organizationCode;
	}

	@Column(name = "companyAddress", length = 45)
	public String getCompanyAddress() {
		return this.companyAddress;
	}

	public void setCompanyAddress(String companyAddress) {
		this.companyAddress = companyAddress;
	}

	@Column(name = "linkMan", length = 45)
	public String getLinkMan() {
		return this.linkMan;
	}

	public void setLinkMan(String linkMan) {
		this.linkMan = linkMan;
	}

	@Column(name = "linkManTelephone", length = 11)
	public String getLinkManTelephone() {
		return this.linkManTelephone;
	}

	public void setLinkManTelephone(String linkManTelephone) {
		this.linkManTelephone = linkManTelephone;
	}

	@Column(name = "companySpaceSize", precision = 22, scale = 0)
	public Double getCompanySpaceSize() {
		return this.companySpaceSize;
	}

	public void setCompanySpaceSize(Double companySpaceSize) {
		this.companySpaceSize = companySpaceSize;
	}

	@Column(name = "companyUsedSpace", precision = 22, scale = 0)
	public Double getCompanyUsedSpace() {
		return this.companyUsedSpace;
	}

	public void setCompanyUsedSpace(Double companyUsedSpace) {
		this.companyUsedSpace = companyUsedSpace;
	}

}
