package com.bigroad.model.db;


// Generated 2015-4-25 13:01:25 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TDepartment generated by hbm2java
 */
@Entity
@Table(name = "T_department", catalog = "CloudFiles")
public class TDepartment implements java.io.Serializable {

	private String departmentId;
	private String departmentName;
	private Double departmentSpaceSize;
	private Double departmentUsedSpace;
	private String departmentDescription;
	private Set<TDepartmentOperation> TDepartmentOperations = new HashSet<TDepartmentOperation>(
			0);
	private Set<TUser> TUsers = new HashSet<TUser>(0);
	private Set<TFile> TFiles = new HashSet<TFile>(0);

	public TDepartment() {
	}

	public TDepartment(String departmentId) {
		this.departmentId = departmentId;
	}

	public TDepartment(String departmentId, String departmentName,
			Double departmentSpaceSize, Double departmentUsedSpace,
			String departmentDescription,
			Set<TDepartmentOperation> TDepartmentOperations, Set<TUser> TUsers,
			Set<TFile> TFiles) {
		this.departmentId = departmentId;
		this.departmentName = departmentName;
		this.departmentSpaceSize = departmentSpaceSize;
		this.departmentUsedSpace = departmentUsedSpace;
		this.departmentDescription = departmentDescription;
		this.TDepartmentOperations = TDepartmentOperations;
		this.TUsers = TUsers;
		this.TFiles = TFiles;
	}

	@Id
	@Column(name = "departmentID", unique = true, nullable = false, length = 100)
	public String getDepartmentId() {
		return this.departmentId;
	}

	public void setDepartmentId(String departmentId) {
		this.departmentId = departmentId;
	}

	@Column(name = "departmentName", length = 45)
	public String getDepartmentName() {
		return this.departmentName;
	}

	public void setDepartmentName(String departmentName) {
		this.departmentName = departmentName;
	}

	@Column(name = "departmentSpaceSize", precision = 22, scale = 0)
	public Double getDepartmentSpaceSize() {
		return this.departmentSpaceSize;
	}

	public void setDepartmentSpaceSize(Double departmentSpaceSize) {
		this.departmentSpaceSize = departmentSpaceSize;
	}

	@Column(name = "departmentUsedSpace", precision = 22, scale = 0)
	public Double getDepartmentUsedSpace() {
		return this.departmentUsedSpace;
	}

	public void setDepartmentUsedSpace(Double departmentUsedSpace) {
		this.departmentUsedSpace = departmentUsedSpace;
	}

	@Column(name = "departmentDescription", length = 2000)
	public String getDepartmentDescription() {
		return this.departmentDescription;
	}

	public void setDepartmentDescription(String departmentDescription) {
		this.departmentDescription = departmentDescription;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TDepartment")
	public Set<TDepartmentOperation> getTDepartmentOperations() {
		return this.TDepartmentOperations;
	}

	public void setTDepartmentOperations(
			Set<TDepartmentOperation> TDepartmentOperations) {
		this.TDepartmentOperations = TDepartmentOperations;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TDepartment")
	public Set<TUser> getTUsers() {
		return this.TUsers;
	}

	public void setTUsers(Set<TUser> TUsers) {
		this.TUsers = TUsers;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TDepartment")
	public Set<TFile> getTFiles() {
		return this.TFiles;
	}

	public void setTFiles(Set<TFile> TFiles) {
		this.TFiles = TFiles;
	}

}
