package com.bigroad.model.db;

// Generated 2015-4-25 13:01:25 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TDraft generated by hbm2java
 */
@Entity
@Table(name = "T_draft", catalog = "CloudFiles")
public class TDraft implements java.io.Serializable {

	private String draftId;
	private TUser TUser;
	private String draftTransactionId;
	private Date draftNewTime;

	public TDraft() {
	}

	public TDraft(String draftId) {
		this.draftId = draftId;
	}

	public TDraft(String draftId, TUser TUser, String draftTransactionId,
			Date draftNewTime) {
		this.draftId = draftId;
		this.TUser = TUser;
		this.draftTransactionId = draftTransactionId;
		this.draftNewTime = draftNewTime;
	}

	@Id
	@Column(name = "draftID", unique = true, nullable = false, length = 100)
	public String getDraftId() {
		return this.draftId;
	}

	public void setDraftId(String draftId) {
		this.draftId = draftId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "draftPersonID")
	public TUser getTUser() {
		return this.TUser;
	}

	public void setTUser(TUser TUser) {
		this.TUser = TUser;
	}

	@Column(name = "draftTransactionID", length = 100)
	public String getDraftTransactionId() {
		return this.draftTransactionId;
	}

	public void setDraftTransactionId(String draftTransactionId) {
		this.draftTransactionId = draftTransactionId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "draftNewTime", length = 19)
	public Date getDraftNewTime() {
		return this.draftNewTime;
	}

	public void setDraftNewTime(Date draftNewTime) {
		this.draftNewTime = draftNewTime;
	}

}
