package com.bigroad.model.db;

// Generated 2015-4-25 13:01:25 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.GenericGenerator;

/**
 * TFile generated by hbm2java
 */
@Entity
@Table(name = "T_file", catalog = "CloudFiles")
public class TFile implements java.io.Serializable {

	private String fileId;
	private TUser TUser;
	private TFile TFile;
	private TDepartment TDepartment;
	private String fileName;
	private Integer fileType;
	private Date fileNewTime;
	private String filePath;
	private String filePrimaryPath;
	private Double fileSize;
	private String fileMd5;
	private String fileExtension;
	private Integer fileAttribute;
	private String fileStoragePath;
	private Set<TFile> TFiles = new HashSet<TFile>(0);
	private Set<TDepartmentOperation> TDepartmentOperations = new HashSet<TDepartmentOperation>(
			0);

	public TFile() {
	}

	public TFile(String fileId) {
		this.fileId = fileId;
	}

	public TFile(String fileId, TUser TUser, TFile TFile,
			TDepartment TDepartment, String fileName, Integer fileType,
			Date fileNewTime, String filePath, String filePrimaryPath,
			Double fileSize, String fileMd5, String fileExtension,
			Integer fileAttribute, String fileStoragePath, Set<TFile> TFiles,
			Set<TDepartmentOperation> TDepartmentOperations) {
		this.fileId = fileId;
		this.TUser = TUser;
		this.TFile = TFile;
		this.TDepartment = TDepartment;
		this.fileName = fileName;
		this.fileType = fileType;
		this.fileNewTime = fileNewTime;
		this.filePath = filePath;
		this.filePrimaryPath = filePrimaryPath;
		this.fileSize = fileSize;
		this.fileMd5 = fileMd5;
		this.fileExtension = fileExtension;
		this.fileAttribute = fileAttribute;
		this.fileStoragePath = fileStoragePath;
		this.TFiles = TFiles;
		this.TDepartmentOperations = TDepartmentOperations;
	}

	@Id
	@GeneratedValue(generator = "uuid")
    @GenericGenerator(name = "uuid", strategy = "uuid")
	@Column(name = "fileID", unique = true, nullable = false, length = 100)
	public String getFileId() {
		return this.fileId;
	}

	public void setFileId(String fileId) {
		this.fileId = fileId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "fileUserID")
	public TUser getTUser() {
		return this.TUser;
	}

	public void setTUser(TUser TUser) {
		this.TUser = TUser;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "folderID")
	public TFile getTFile() {
		return this.TFile;
	}

	public void setTFile(TFile TFile) {
		this.TFile = TFile;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "fileDepartmentID")
	public TDepartment getTDepartment() {
		return this.TDepartment;
	}

	public void setTDepartment(TDepartment TDepartment) {
		this.TDepartment = TDepartment;
	}

	@Column(name = "fileName", length = 45)
	public String getFileName() {
		return this.fileName;
	}

	public void setFileName(String fileName) {
		this.fileName = fileName;
	}

	@Column(name = "fileType")
	public Integer getFileType() {
		return this.fileType;
	}

	public void setFileType(Integer fileType) {
		this.fileType = fileType;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fileNewTime", length = 19)
	public Date getFileNewTime() {
		return this.fileNewTime;
	}

	public void setFileNewTime(Date fileNewTime) {
		this.fileNewTime = fileNewTime;
	}

	@Column(name = "filePath", length = 2000)
	public String getFilePath() {
		return this.filePath;
	}

	public void setFilePath(String filePath) {
		this.filePath = filePath;
	}

	@Column(name = "filePrimaryPath", length = 2000)
	public String getFilePrimaryPath() {
		return this.filePrimaryPath;
	}

	public void setFilePrimaryPath(String filePrimaryPath) {
		this.filePrimaryPath = filePrimaryPath;
	}

	@Column(name = "fileSize", precision = 22, scale = 0)
	public Double getFileSize() {
		return this.fileSize;
	}

	public void setFileSize(Double fileSize) {
		this.fileSize = fileSize;
	}

	@Column(name = "fileMD5", length = 2000)
	public String getFileMd5() {
		return this.fileMd5;
	}

	public void setFileMd5(String fileMd5) {
		this.fileMd5 = fileMd5;
	}

	@Column(name = "fileExtension", length = 45)
	public String getFileExtension() {
		return this.fileExtension;
	}

	public void setFileExtension(String fileExtension) {
		this.fileExtension = fileExtension;
	}

	@Column(name = "fileAttribute")
	public Integer getFileAttribute() {
		return this.fileAttribute;
	}

	public void setFileAttribute(Integer fileAttribute) {
		this.fileAttribute = fileAttribute;
	}

	@Column(name = "fileStoragePath", length = 500)
	public String getFileStoragePath() {
		return this.fileStoragePath;
	}

	public void setFileStoragePath(String fileStoragePath) {
		this.fileStoragePath = fileStoragePath;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TFile")
	public Set<TFile> getTFiles() {
		return this.TFiles;
	}

	public void setTFiles(Set<TFile> TFiles) {
		this.TFiles = TFiles;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TFile")
	public Set<TDepartmentOperation> getTDepartmentOperations() {
		return this.TDepartmentOperations;
	}

	public void setTDepartmentOperations(
			Set<TDepartmentOperation> TDepartmentOperations) {
		this.TDepartmentOperations = TDepartmentOperations;
	}

}
