package com.bigroad.model.db;

// Generated 2015-4-25 13:01:25 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TPrivateMessage generated by hbm2java
 */
@Entity
@Table(name = "T_privateMessage", catalog = "CloudFiles")
public class TPrivateMessage implements java.io.Serializable {

	private String privateMessageId;
	private TUser TUserByReceivePersonId;
	private TUser TUserBySentPersonId;
	private Date privateMessageSentTime;
	private String privateMessageSentContent;

	public TPrivateMessage() {
	}

	public TPrivateMessage(String privateMessageId) {
		this.privateMessageId = privateMessageId;
	}

	public TPrivateMessage(String privateMessageId,
			TUser TUserByReceivePersonId, TUser TUserBySentPersonId,
			Date privateMessageSentTime, String privateMessageSentContent) {
		this.privateMessageId = privateMessageId;
		this.TUserByReceivePersonId = TUserByReceivePersonId;
		this.TUserBySentPersonId = TUserBySentPersonId;
		this.privateMessageSentTime = privateMessageSentTime;
		this.privateMessageSentContent = privateMessageSentContent;
	}

	@Id
	@Column(name = "privateMessageID", unique = true, nullable = false, length = 100)
	public String getPrivateMessageId() {
		return this.privateMessageId;
	}

	public void setPrivateMessageId(String privateMessageId) {
		this.privateMessageId = privateMessageId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "receivePersonID")
	public TUser getTUserByReceivePersonId() {
		return this.TUserByReceivePersonId;
	}

	public void setTUserByReceivePersonId(TUser TUserByReceivePersonId) {
		this.TUserByReceivePersonId = TUserByReceivePersonId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "sentPersonID")
	public TUser getTUserBySentPersonId() {
		return this.TUserBySentPersonId;
	}

	public void setTUserBySentPersonId(TUser TUserBySentPersonId) {
		this.TUserBySentPersonId = TUserBySentPersonId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "privateMessageSentTime", length = 19)
	public Date getPrivateMessageSentTime() {
		return this.privateMessageSentTime;
	}

	public void setPrivateMessageSentTime(Date privateMessageSentTime) {
		this.privateMessageSentTime = privateMessageSentTime;
	}

	@Column(name = "privateMessageSentContent", length = 2000)
	public String getPrivateMessageSentContent() {
		return this.privateMessageSentContent;
	}

	public void setPrivateMessageSentContent(String privateMessageSentContent) {
		this.privateMessageSentContent = privateMessageSentContent;
	}

}
