package com.bigroad.model.db;

// Generated 2015-4-25 13:01:25 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TSentTransaction generated by hbm2java
 */
@Entity
@Table(name = "T_sentTransaction", catalog = "CloudFiles")
public class TSentTransaction implements java.io.Serializable {

	private String sentTransactionId;
	private TTransaction TTransaction;
	private TUser TUserBySentTransactioncolPersonId;
	private TUser TUserByReceiveTransactionPersonId;
	private Date sentTransactionTime;
	private String transactionState;

	public TSentTransaction() {
	}

	public TSentTransaction(String sentTransactionId) {
		this.sentTransactionId = sentTransactionId;
	}

	public TSentTransaction(String sentTransactionId,
			TTransaction TTransaction, TUser TUserBySentTransactioncolPersonId,
			TUser TUserByReceiveTransactionPersonId, Date sentTransactionTime,
			String transactionState) {
		this.sentTransactionId = sentTransactionId;
		this.TTransaction = TTransaction;
		this.TUserBySentTransactioncolPersonId = TUserBySentTransactioncolPersonId;
		this.TUserByReceiveTransactionPersonId = TUserByReceiveTransactionPersonId;
		this.sentTransactionTime = sentTransactionTime;
		this.transactionState = transactionState;
	}

	@Id
	@Column(name = "sentTransactionID", unique = true, nullable = false, length = 100)
	public String getSentTransactionId() {
		return this.sentTransactionId;
	}

	public void setSentTransactionId(String sentTransactionId) {
		this.sentTransactionId = sentTransactionId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "transactionID")
	public TTransaction getTTransaction() {
		return this.TTransaction;
	}

	public void setTTransaction(TTransaction TTransaction) {
		this.TTransaction = TTransaction;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "sentTransactioncolPersonID")
	public TUser getTUserBySentTransactioncolPersonId() {
		return this.TUserBySentTransactioncolPersonId;
	}

	public void setTUserBySentTransactioncolPersonId(
			TUser TUserBySentTransactioncolPersonId) {
		this.TUserBySentTransactioncolPersonId = TUserBySentTransactioncolPersonId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "receiveTransactionPersonID")
	public TUser getTUserByReceiveTransactionPersonId() {
		return this.TUserByReceiveTransactionPersonId;
	}

	public void setTUserByReceiveTransactionPersonId(
			TUser TUserByReceiveTransactionPersonId) {
		this.TUserByReceiveTransactionPersonId = TUserByReceiveTransactionPersonId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "sentTransactionTime", length = 19)
	public Date getSentTransactionTime() {
		return this.sentTransactionTime;
	}

	public void setSentTransactionTime(Date sentTransactionTime) {
		this.sentTransactionTime = sentTransactionTime;
	}

	@Column(name = "transactionState", length = 45)
	public String getTransactionState() {
		return this.transactionState;
	}

	public void setTransactionState(String transactionState) {
		this.transactionState = transactionState;
	}

}
