package com.bigroad.model.db;

// Generated 2015-4-25 13:01:25 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TTransactionMessage generated by hbm2java
 */
@Entity
@Table(name = "T_transactionMessage", catalog = "CloudFiles")
public class TTransactionMessage implements java.io.Serializable {

	private String transactionMessageId;
	private TTransaction TTransaction;
	private TUser TUser;
	private Date transactionMessageSentTime;
	private String transactionMessageSentContent;

	public TTransactionMessage() {
	}

	public TTransactionMessage(String transactionMessageId) {
		this.transactionMessageId = transactionMessageId;
	}

	public TTransactionMessage(String transactionMessageId,
			TTransaction TTransaction, TUser TUser,
			Date transactionMessageSentTime,
			String transactionMessageSentContent) {
		this.transactionMessageId = transactionMessageId;
		this.TTransaction = TTransaction;
		this.TUser = TUser;
		this.transactionMessageSentTime = transactionMessageSentTime;
		this.transactionMessageSentContent = transactionMessageSentContent;
	}

	@Id
	@Column(name = "transactionMessageID", unique = true, nullable = false, length = 100)
	public String getTransactionMessageId() {
		return this.transactionMessageId;
	}

	public void setTransactionMessageId(String transactionMessageId) {
		this.transactionMessageId = transactionMessageId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "transactionID")
	public TTransaction getTTransaction() {
		return this.TTransaction;
	}

	public void setTTransaction(TTransaction TTransaction) {
		this.TTransaction = TTransaction;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "userID")
	public TUser getTUser() {
		return this.TUser;
	}

	public void setTUser(TUser TUser) {
		this.TUser = TUser;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "transactionMessageSentTime", length = 19)
	public Date getTransactionMessageSentTime() {
		return this.transactionMessageSentTime;
	}

	public void setTransactionMessageSentTime(Date transactionMessageSentTime) {
		this.transactionMessageSentTime = transactionMessageSentTime;
	}

	@Column(name = "transactionMessageSentContent", length = 2000)
	public String getTransactionMessageSentContent() {
		return this.transactionMessageSentContent;
	}

	public void setTransactionMessageSentContent(
			String transactionMessageSentContent) {
		this.transactionMessageSentContent = transactionMessageSentContent;
	}

}
