package com.bigroad.model.db;

// Generated 2015-4-25 13:01:25 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TTransaction generated by hbm2java
 */
@Entity
@Table(name = "T_transaction", catalog = "CloudFiles")
public class TTransaction implements java.io.Serializable {

	private String transactionId;
	private String transactionName;
	private String transactionContent;
	private String transactionAttachmentAddress;
	private Set<TSentTransaction> TSentTransactions = new HashSet<TSentTransaction>(
			0);
	private Set<TTransactionMessage> TTransactionMessages = new HashSet<TTransactionMessage>(
			0);

	public TTransaction() {
	}

	public TTransaction(String transactionId) {
		this.transactionId = transactionId;
	}

	public TTransaction(String transactionId, String transactionName,
			String transactionContent, String transactionAttachmentAddress,
			Set<TSentTransaction> TSentTransactions,
			Set<TTransactionMessage> TTransactionMessages) {
		this.transactionId = transactionId;
		this.transactionName = transactionName;
		this.transactionContent = transactionContent;
		this.transactionAttachmentAddress = transactionAttachmentAddress;
		this.TSentTransactions = TSentTransactions;
		this.TTransactionMessages = TTransactionMessages;
	}

	@Id
	@Column(name = "transactionID", unique = true, nullable = false, length = 100)
	public String getTransactionId() {
		return this.transactionId;
	}

	public void setTransactionId(String transactionId) {
		this.transactionId = transactionId;
	}

	@Column(name = "transactionName", length = 45)
	public String getTransactionName() {
		return this.transactionName;
	}

	public void setTransactionName(String transactionName) {
		this.transactionName = transactionName;
	}

	@Column(name = "transactionContent", length = 2000)
	public String getTransactionContent() {
		return this.transactionContent;
	}

	public void setTransactionContent(String transactionContent) {
		this.transactionContent = transactionContent;
	}

	@Column(name = "transactionAttachmentAddress", length = 45)
	public String getTransactionAttachmentAddress() {
		return this.transactionAttachmentAddress;
	}

	public void setTransactionAttachmentAddress(
			String transactionAttachmentAddress) {
		this.transactionAttachmentAddress = transactionAttachmentAddress;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TTransaction")
	public Set<TSentTransaction> getTSentTransactions() {
		return this.TSentTransactions;
	}

	public void setTSentTransactions(Set<TSentTransaction> TSentTransactions) {
		this.TSentTransactions = TSentTransactions;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TTransaction")
	public Set<TTransactionMessage> getTTransactionMessages() {
		return this.TTransactionMessages;
	}

	public void setTTransactionMessages(
			Set<TTransactionMessage> TTransactionMessages) {
		this.TTransactionMessages = TTransactionMessages;
	}

}
